### ISSUE TITLE
دسته بندی

### ISSUE THREAD

**Issue by GameO7er** [softwaretalks/awesome-persian-youtube#5]
سلام و عرض ادب و احترام.
اجازه مشارکت و دسته بندی کانال ها هست؟
اگر جواب مثبت هست دسته بندی خاصی مد نظرتون هست تا انجام بدم یا خیر؟

با نهایت تشکر

**Comment by Hameds** [comment]
@GameO7er مشارکت که همیشه مورد استقباله اما در مورد دسته‌بندی فعلاً نیازی نیست البته اگر پیشنهادی برای دسته‌بندی دارید بفرمایید

**Comment by Hameds** [comment]
با توجه به اینکه [اپلیکیشن گلچین](https://golchin.io/apps)  اومده و دسته‌بندی‌های متنوعی از جمله دسته‌بندی این لیست رو داره فعلا این مخزن بسته می‌شه
